apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.9.12-alpine3.15
    command:
    - sleep
    args:
    - infinity
  hostAliases:
  - ip: "127.21.0.50"
    hostnames:
    - "gitea.localhost.com"